// export function getAllProductsApi(qs, cookies) {
//   return http
//     .get(`/product/list?${qs}`, {
//       headers: {
//         Cookie: cookies,
//       },
//     })
//     .then(({ data }) => data.data);
// }
export async function fetchOrders(status) {
  // شبیه‌سازی API call
  await new Promise((r) => setTimeout(r, 300));

  return [
    {
      id: "123445",
      date: "1404/07/15",
      price: 10271000,
      offPrice: 1599000,
      items: [
        {
          id: "1",
          enTitle: "Tiziana Terenzi",
          perTitle: "تیزیانا ترنزی",
          src: "/images/perfume-1.svg",
          alt: "perfume image",
          type: "decant",
          price: 1240000,
          offValue: 20,
          volume: 20,
        },
        {
          id: "2",
          enTitle: "Tiziana Terenzi",
          perTitle: "شنل اگویست پلاتینیوم",
          src: "/images/perfume-2.svg",
          alt: "perfume image",
          type: "seald",
          price: 4480000,
          offValue: 10,
          volume: 100,
        },
        {
          id: "3",
          enTitle: "Tiziana Terenzi",
          perTitle: "تیزیانا ترنزی",
          src: "/images/perfume-3.svg",
          alt: "perfume image",
          type: "sealed",
          price: 5760000,
          offValue: 15,
          volume: 105,
        },
        {
          id: "4",
          enTitle: "Tiziana Terenzi",
          perTitle: "شنل اگویست پلاتینیوم",
          src: "/images/perfume-2.svg",
          alt: "perfume image",
          type: "decant",
          price: 390000,
          offValue: 10,
          volume: 5,
        },
      ],
    },
    {
      id: "123446",
      date: "1404/07/16",
      price: 1000000,
      items: [
        {
          id: "1",
          enTitle: "Tiziana Terenzi",
          perTitle: "تیزیانا ترنزی",
          src: "/images/perfume-1.svg",
          alt: "perfume image",
          price: 1240000,
          offValue: 20,
        },
        {
          id: "2",
          enTitle: "Tiziana Terenzi",
          perTitle: "شنل اگویست پلاتینیوم",
          src: "/images/perfume-2.svg",
          alt: "perfume image",
          price: 1390000,
          offValue: 10,
        },
        {
          id: "3",
          enTitle: "Tiziana Terenzi",
          perTitle: "تیزیانا ترنزی",
          src: "/images/perfume-3.svg",
          alt: "perfume image",
          price: 1780000,
          offValue: 15,
        },
      ],
    },
    {
      id: "123447",
      date: "1404/07/18",
      price: 1100000,
      items: [
        {
          id: "1",
          enTitle: "Tiziana Terenzi",
          perTitle: "تیزیانا ترنزی",
          src: "/images/perfume-1.svg",
          alt: "perfume image",
          price: 1240000,
          offValue: 20,
        },
        {
          id: "2",
          enTitle: "Tiziana Terenzi",
          perTitle: "شنل اگویست پلاتینیوم",
          src: "/images/perfume-2.svg",
          alt: "perfume image",
          price: 1390000,
          offValue: 10,
        },
        {
          id: "3",
          enTitle: "Tiziana Terenzi",
          perTitle: "تیزیانا ترنزی",
          src: "/images/perfume-3.svg",
          alt: "perfume image",
          price: 1780000,
          offValue: 15,
        },
      ],
    },
    {
      id: "123448",
      date: "1404/07/22",
      price: 1000000,
      items: [
        {
          id: "1",
          enTitle: "Tiziana Terenzi",
          perTitle: "تیزیانا ترنزی",
          src: "/images/perfume-1.svg",
          alt: "perfume image",
          price: 1240000,
          offValue: 20,
        },
        {
          id: "2",
          enTitle: "Tiziana Terenzi",
          perTitle: "شنل اگویست پلاتینیوم",
          src: "/images/perfume-2.svg",
          alt: "perfume image",
          price: 1390000,
          offValue: 10,
        },
        {
          id: "3",
          enTitle: "Tiziana Terenzi",
          perTitle: "تیزیانا ترنزی",
          src: "/images/perfume-3.svg",
          alt: "perfume image",
          price: 1780000,
          offValue: 15,
        },
      ],
    },
    {
      id: "123449",
      date: "1404/07/22",
      price: 1000000,
      items: [
        {
          id: "1",
          enTitle: "Tiziana Terenzi",
          perTitle: "تیزیانا ترنزی",
          src: "/images/perfume-1.svg",
          alt: "perfume image",
          price: 1240000,
          offValue: 20,
        },
        {
          id: "2",
          enTitle: "Tiziana Terenzi",
          perTitle: "شنل اگویست پلاتینیوم",
          src: "/images/perfume-2.svg",
          alt: "perfume image",
          price: 1390000,
          offValue: 10,
        },
        {
          id: "3",
          enTitle: "Tiziana Terenzi",
          perTitle: "تیزیانا ترنزی",
          src: "/images/perfume-3.svg",
          alt: "perfume image",
          price: 1780000,
          offValue: 15,
        },
      ],
    },
    {
      id: "123450",
      date: "1404/07/22",
      price: 1000000,
      items: [
        {
          id: "1",
          enTitle: "Tiziana Terenzi",
          perTitle: "تیزیانا ترنزی",
          src: "/images/perfume-1.svg",
          alt: "perfume image",
          price: 1240000,
          offValue: 20,
        },
        {
          id: "2",
          enTitle: "Tiziana Terenzi",
          perTitle: "شنل اگویست پلاتینیوم",
          src: "/images/perfume-2.svg",
          alt: "perfume image",
          price: 1390000,
          offValue: 10,
        },
        {
          id: "3",
          enTitle: "Tiziana Terenzi",
          perTitle: "تیزیانا ترنزی",
          src: "/images/perfume-3.svg",
          alt: "perfume image",
          price: 1780000,
          offValue: 15,
        },
      ],
    },
    {
      id: "123451",
      date: "1404/07/22",
      price: 1000000,
      items: [
        {
          id: "1",
          enTitle: "Tiziana Terenzi",
          perTitle: "تیزیانا ترنزی",
          src: "/images/perfume-1.svg",
          alt: "perfume image",
          price: 1240000,
          offValue: 20,
        },
        {
          id: "2",
          enTitle: "Tiziana Terenzi",
          perTitle: "شنل اگویست پلاتینیوم",
          src: "/images/perfume-2.svg",
          alt: "perfume image",
          price: 1390000,
          offValue: 10,
        },
        {
          id: "3",
          enTitle: "Tiziana Terenzi",
          perTitle: "تیزیانا ترنزی",
          src: "/images/perfume-3.svg",
          alt: "perfume image",
          price: 1780000,
          offValue: 15,
        },
      ],
    },
  ];
}
