export const volumes = [
  {
    id: 1,
    quantity: 3,
    value: "3 ml",
    title: "۳ میل",
    description: "حجم ۳ میل",
  },
  {
    id: 2,
    quantity: 5,
    value: "5 ml",
    title: "۵ میل",
    description: "حجم ۵ میل",
  },
  {
    id: 3,
    quantity: 10,
    value: "10 ml",
    title: "۱۰ میل",
    description: "حجم ۱۰ میل",
  },
  {
    id: 4,
    quantity: 20,
    value: "20 ml",
    title: "۲۰ میل",
    description: "حجم ۲۰ میل",
  },
  {
    id: 5,
    quantity: 25,
    value: "25 ml",
    title: "۲۵ میل",
    description: "حجم ۲۵ میل",
  },
  {
    id: 6,
    quantity: 30,
    value: "30 ml",
    title: "۳۰ میل",
    description: "حجم ۳۰ میل",
  },
  {
    id: 7,
    quantity: 50,
    value: "50 ml",
    title: "۵۰ میل",
    description: "حجم ۵۰ میل",
  },
  {
    id: 8,
    quantity: 75,
    value: "75 ml",
    title: "۷۵ میل",
    description: "حجم ۷۵ میل",
  },
  {
    id: 9,
    quantity: 100,
    value: "100 ml",
    title: "۱۰۰ میل",
    description: "حجم ۱۰۰ میل",
  },
  {
    id: 10,
    quantity: 105,
    value: "105 ml",
    title: "۱۰۵ میل",
    description: "حجم ۱۰۵ میل",
  },
  {
    id: 11,
    quantity: 120,
    value: "120 ml",
    title: "۱۲۰ میل",
    description: "حجم ۱۲۰ میل",
  },
  {
    id: 12,
    quantity: 125,
    value: "125 ml",
    title: "۱۲۵ میل",
    description: "حجم ۱۲۵ میل",
  },
  {
    id: 13,
    quantity: 150,
    value: "150 ml",
    title: "۱۵۰ میل",
    description: "حجم ۱۵۰ میل",
  },
  {
    id: 14,
    quantity: 200,
    value: "200 ml",
    title: "۲۰۰ میل",
    description: "حجم ۲۰۰ میل",
  },
];

// function generateVolumes(numbers) {
//   return numbers.map((num, index) => ({
//     id: index + 1,
//     quantity: num,
//     value: `volume-${num}`,
//     title: `${num} میل`,
//     description: `حجم ${num} میل`,
//     iconeUrl: `volume-${num}.svg`,
//   }));
// }
