export const volumes = [
  {
    id: 1,
    quantity: 3,
    value: "volume-3",
    title: "۳ میل",
    description: "حجم ۳ میل",
    iconeUrl: "volume-3.svg",
  },
  {
    id: 2,
    quantity: 5,
    value: "volume-5",
    title: "۵ میل",
    description: "حجم ۵ میل",
    iconeUrl: "volume-5.svg",
  },
  {
    id: 3,
    quantity: 10,
    value: "volume-10",
    title: "۱۰ میل",
    description: "حجم ۱۰ میل",
    iconeUrl: "volume-10.svg",
  },
  {
    id: 4,
    quantity: 20,
    value: "volume-20",
    title: "۲۰ میل",
    description: "حجم ۲۰ میل",
    iconeUrl: "volume-20.svg",
  },
  {
    id: 5,
    quantity: 25,
    value: "volume-25",
    title: "۲۵ میل",
    description: "حجم ۲۵ میل",
    iconeUrl: "volume-25.svg",
  },
  {
    id: 6,
    quantity: 30,
    value: "volume-30",
    title: "۳۰ میل",
    description: "حجم ۳۰ میل",
    iconeUrl: "volume-30.svg",
  },
  {
    id: 7,
    quantity: 50,
    value: "volume-50",
    title: "۵۰ میل",
    description: "حجم ۵۰ میل",
    iconeUrl: "volume-50.svg",
  },
  {
    id: 8,
    quantity: 75,
    value: "volume-75",
    title: "۷۵ میل",
    description: "حجم ۷۵ میل",
    iconeUrl: "volume-75.svg",
  },
  {
    id: 9,
    quantity: 100,
    value: "volume-100",
    title: "۱۰۰ میل",
    description: "حجم ۱۰۰ میل",
    iconeUrl: "volume-100.svg",
  },
  {
    id: 10,
    quantity: 105,
    value: "volume-105",
    title: "۱۰۵ میل",
    description: "حجم ۱۰۵ میل",
    iconeUrl: "volume-105.svg",
  },
  {
    id: 11,
    quantity: 120,
    value: "volume-120",
    title: "۱۲۰ میل",
    description: "حجم ۱۲۰ میل",
    iconeUrl: "volume-120.svg",
  },
  {
    id: 12,
    quantity: 125,
    value: "volume-125",
    title: "۱۲۵ میل",
    description: "حجم ۱۲۵ میل",
    iconeUrl: "volume-125.svg",
  },
  {
    id: 13,
    quantity: 150,
    value: "volume-150",
    title: "۱۵۰ میل",
    description: "حجم ۱۵۰ میل",
    iconeUrl: "volume-150.svg",
  },
  {
    id: 14,
    quantity: 200,
    value: "volume-200",
    title: "۲۰۰ میل",
    description: "حجم ۲۰۰ میل",
    iconeUrl: "volume-200.svg",
  },
];

// function generateVolumes(numbers) {
//   return numbers.map((num, index) => ({
//     id: index + 1,
//     quantity: num,
//     value: `volume-${num}`,
//     title: `${num} میل`,
//     description: `حجم ${num} میل`,
//     iconeUrl: `volume-${num}.svg`,
//   }));
// }
